# Generated by Django 4.0.5 on 2022-08-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=64, null=True)),
                ('lastname', models.CharField(blank=True, max_length=64, null=True)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, choices=[('M', 'Member'), ('O', 'Owner'), ('A', 'Admin')], max_length=64, null=True)),
                ('likes_dogs', models.BooleanField()),
                ('likes_cats', models.BooleanField()),
                ('dob', models.DateField()),
                ('bio', models.TextField()),
            ],
        ),
    ]
