# Generated by Django 4.0.5 on 2022-09-09 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_person_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id'], 'verbose_name_plural': 'People'},
        ),
    ]
